// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Data.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20220406142827_ajuste pk id")]
    partial class ajustepkid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.TabTelecomConsolidado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal (18,2)");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("DateTime");

                    b.Property<int>("Disparos")
                        .HasColumnType("int");

                    b.Property<int>("Fila")
                        .HasColumnType("int");

                    b.Property<string>("Servidor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusFinal")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusInicial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Terminator")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TabTelecomConsolidado");
                });
#pragma warning restore 612, 618
        }
    }
}
